# Release
version=2.5.10
group=com.nine.softimprints
java_version=25
# Publishing
loaders=
publishing_task=
required_mods=
loader_display=
supported_mc_versions=26.2-rc-2
mod_display_name=SoftImprints
mc_display_version=26.2-rc-2
version_type=stable
modrinth_id=UhxJgB1o
curseforge_id=1474300
fabric_release_type=release
neoforge_release_type=release
publish_game_versions=26.2-rc-2
# Common
mod_name=Soft Imprints
mod_author=Nine
mod_id=softimprints
license=MIT
credits=
description=Block imprints while walking
homepage=https://www.curseforge.com/minecraft/mc-mods/snow-imprints
sources=https://github.com/0Templ/SoftImprints
issues=https://github.com/0Templ/SoftImprints/issues
# Minecraft Target
minecraft_version=26.2-rc-2
minecraft_version_range=[26.2, 27)
minecraft_version_constraint=26.2.x
neo_form_version=26.2-rc-2-1
parchment_minecraft=1.21.8
parchment_version=2025.07.20
# Fabric
# https://fabricmc.net/develop/
fabric_version=0.152.0+26.2
fabric_loader_version=0.19.3
# NeoForge
# https://projects.neoforged.net/neoforged/neoforge/
neoforge_version=26.1.2.30-beta
neoforge_loader_version_range=[4,)
# Compat
night_config_version=3.8.4
mod_menu_version=20.0.0-beta.2
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
