# Release
version=2.5.17
group=com.nine.softimprints
java_version=25
# Publishing
loaders=
publishing_task=
required_mods=
loader_display=

mod_display_name=SoftImprints
mc_display_version=26.3-snapshot-1
version_type=beta
curseforge_id=1474300
modrinth_id=UhxJgB1o
publish_game_versions=26.3-snapshot
publish_game_versions_curseforge=26.1-snapshot
publish_game_versions_modrinth=
# Common
mod_name=Soft Imprints
mod_author=Nine
mod_id=softimprints
license=MIT
credits=
description=Block imprints while walking
homepage=https://www.curseforge.com/minecraft/mc-mods/snow-imprints
sources=https://github.com/0Templ/SoftImprints
issues=https://github.com/0Templ/SoftImprints/issues
# Minecraft Target
minecraft_version=26.3-snapshot-1
minecraft_version_range=[26.3, 27)
minecraft_version_constraint=~26.3-
# Fabric

# https://fabricmc.net/develop/
fabric_version_minimum=0.153.1+26.3
fabric_version=0.153.1+26.3
fabric_loader_version=0.19.3
# NeoForge
# https://projects.neoforged.net/neoforged/neoforge/
neoforge_version=26.2.0.0-beta
neoforge_loader_version_range=[4,)
neo_form_version=26.3-snapshot-1-1
# Compat
night_config_version=3.9.0
mod_menu_version=20.0.0-beta.2
# Gradle
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
