modLoader = "javafml"
loaderVersion = "${neoforge_loader_version_range}"
license = "${license}"

[[mods]]
modId = "${mod_id}"
version = "${version}"
displayName = "${mod_name}"
logoFile = "assets/softimprints/textures/icon/icon.png"
logoBlur = false
authors = "${mod_author}"
description = '''${description}'''
displayURL = "${sources}"
modUrl = "${homepage}"
updateJSONURL = "https://raw.githubusercontent.com/0Templ/ModVersions/refs/heads/main/neoforge/snow-imprints/v1/26.1.2.json"

[[mixins]]
config = "${mod_id}.mixins.json"

[[mixins]]
config = "${mod_id}.neoforge.mixins.json"

[[dependencies.${ mod_id }]]
modId = "neoforge"
type = "required"
versionRange = "${neoforge_loader_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.${ mod_id }]]
modId = "eclipticseasons"
type = "optional"
versionRange = "[0,)"
ordering = "AFTER"
side = "CLIENT"
