plugins {
    id 'multiloader-loader'
    id 'net.neoforged.moddev'
    id 'me.shedaniel.unified-publishing'
}

neoForge {
    version = neoforge_version

    def at = project(':common').file('src/main/resources/META-INF/accesstransformer.cfg')
    if (at.exists()) {
        accessTransformers.from(at.absolutePath)
    }
    parchment {
        minecraftVersion = parchment_minecraft
        mappingsVersion = parchment_version
    }
    runs {
        configureEach {
            systemProperty 'neoforge.enabledGameTestNamespaces', mod_id
            ideName = "NeoForge ${it.name.capitalize()} (${project.path})"
        }
        client {
            client()
            gameDirectory = mkdir(file("runs/client"))
        }
        data {
            clientData()
            gameDirectory = mkdir(file("runs/data"))
            programArguments.addAll '--mod', project.mod_id, '--all', '--output', file('src/generated/resources/').getAbsolutePath(), '--existing', file('src/main/resources/').getAbsolutePath()
        }
        server {
            server()
            gameDirectory = mkdir(file("runs/server"))
        }
    }
    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

dependencies {

    // Ecliptic seasons
    compileOnly("curse.maven:ecliptic-seasons-1118306:7982672")
    runtimeOnly("curse.maven:ecliptic-seasons-1118306:7982672")

    // World edit
    runtimeOnly "curse.maven:worldedit-225608:7903183"

    compileOnly "com.electronwill.night-config:core:${night_config_version}"
    compileOnly "com.electronwill.night-config:toml:${night_config_version}"
    

}

sourceSets.main.resources.srcDir 'src/generated/resources'

tasks.named('jar', Jar) {
    includeEmptyDirs = false
    exclude '.cache/**'
}

def loaderAttribute = Attribute.of('io.github.mcgradleconventions.loader', String)
def markNeoForge = { String configName ->
    configurations.named(configName) {
        attributes {
            attribute(loaderAttribute, 'neoforge')
        }
    }
}

['apiElements', 'runtimeElements', 'sourcesElements', 'javadocElements'].each(markNeoForge)

sourceSets.configureEach {
    [compileClasspathConfigurationName, runtimeClasspathConfigurationName, getTaskName(null, 'jarJar')]
            .each(markNeoForge)
}

configureUnifiedPublishing(project, [
        loaderName     : 'NeoForge',
        gameLoader     : 'neoforge',
        releaseType: rootProject.neoforge_release_type,
        publicationTask: 'jar'
])
